name: Build and Test

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Run unit tests
      run: ./gradlew test --continue

    - name: Build mobile app
      run: ./gradlew :app:mobile:assembleDebug

    - name: Build TV app
      run: ./gradlew :app:tv:assembleDebug

    - name: Build release APKs
      run: |
        ./gradlew :app:mobile:assembleRelease
        ./gradlew :app:tv:assembleRelease

    - name: Upload mobile artifacts
      uses: actions/upload-artifact@v4
      with:
        name: mobile-apk
        path: app/mobile/build/outputs/apk/release/

    - name: Upload TV artifacts
      uses: actions/upload-artifact@v4
      with:
        name: tv-apk
        path: app/tv/build/outputs/apk/release/